Reduce desyncing issue
Fustigate8933/UtaYaku pull request #1
Opened 2024-12-23 05:51 UTC by nut1414

1. Some song has pauses with no lyric, causing the breakdown to desync.
2. Adding additional prompt (use more token) to not look ahead and merge breakdown line which will cause desync. 
(still have some desync but probably could be improve by giving the model array[string] instead of string with /n)

Some feedback:
- Having some code formatter(Eslint, Prettier) would be pretty awesome for code consistency!

I have a branch I am personally using based on [song-search](https://github.com/Fustigate8933/UtaYaku/tree/song-search) branch which have some improvement (fix overflow, change some layout...) you can check it out on [fix-song-search](https://github.com/nut1414/UtaYaku/tree/fix_sync_song_search) :)

2024-12-24 03:20 UTC, Fustigate8933 commented
Hi, thanks for the contribution! I have fixed the desynchronization issue in the song search branch. I'm pretty new to this, this is my first pull request ever.
I'll review your branch and merge it if everything seems fine

2024-12-25 09:27 UTC, Fustigate8933 commented
I see that you are importing stuff like refs. In Nuxt it is automatically imported. Is it convention to include it?

2024-12-25 09:41 UTC, nut1414 commented
For the import, I that it is already there from the start since it a .ts file and not vue file just added semicolon

I think its because typescript code extension/Github Copilot on my IDE auto formatted it. Generally semi-colons are up to the project owner code style if they wanted it or not since it is optional. 

Normally a linter/code fornatter that the owner setup in the project would handle styling to ensure consistency and prevent merge conflict.

2024-12-25 09:44 UTC, nut1414 commented
I have never work on a Nuxt/Vue based project before, feel free to comment if it doesn't match match their convention!

2024-12-25 09:48 UTC, Fustigate8933 requested changes
* Importing { ref } may be unnecessary
* Extra examples for the model increases tokens used, so need more money to run model. Maybe consider adding an option for the user?

2025-01-07 14:17 UTC, closed without merging